# 确保 mirai 安装了 mirai-api-http

# api-http 的地址
host: localhost:8080
# api-http 中的 authKey 用于验证身份
Key: 123456
# bot 的QQ
botID: 123456789
# bot 默认启用的群号
groupID: 987654321
# 启用bot
enable_Bot: false

# 将转发消息保存到cache文件夹中
# 此方法可以做到节约服务器运行内存
# 但是会占用存储内存

# 如果为 false，则服务器一关闭，所有转发消息将会被释放，并且下次启动时无法查看。
# 如果为 true，则会将缓存消息存到本地，下次启动时依旧可以查看。
saveCache: false

# 游戏消息转发到群里的间隔
# 防止莫名其妙的转发不了游戏内的消息
# 单位为 tick, 每 20tick 为 1s
sendDelay: 10

# 验证消息失效时间， 单位: 分钟
time: 5
# 验证码位数
codeLength: 6

# 时间格式
# 用于展示群消息发送时间
timeFormat: yyyy.MM.dd HH:mm:ss

# QQ号的正则表达式， 用于绑定时检测有没有输入正确的QQ号
regex: '[1-9][0-9]{8,10}'

# 调试模式
# 非必要无需打开
# 否则只会增多无用的日志输出！
DEBUG: false

#消息抓取默认设置
catch:
  # 消息抓取的类型
  # text 为只抓取纯文本类消息
  # multi 为抓取复合消息
  # ## 只有当此选项为 multi 类型时
  # img, at, emoji 等类型的抓取才有效
  type: multi
  # 如果为multi 则下面选项中必须有一个为true
  # 否则将不会向游戏内推送消息e
  # 抓取纯文本消息
  text: true
  # 抓取图片消息
  img: true
  # 抓取at消息
  at: true
  # 抓取 [@全体成员]
  atAll: true
  # 抓取face表情
  face: true
  # 抓取转发消息
  forward: true

